version: '3.7'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=unleash
      - POSTGRES_USER=unleash
      - POSTGRES_DB=unleash

  unleash:
    build:
      context: ./server
    ports: 
      - 4242:4242
    depends_on:
      - db